server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enable: Always

logging:
  level:
    root: INFO
    com.ead: TRACE
    org.hibernate: INFO
    org.springframework.web: INFO

ead:
  api:
    url:
      course: 'http://localhost:8082'